USE DATABASE RETAIL_LAKEHOUSE;
USE SCHEMA STAGING;

COPY INTO CUSTOMERS
FROM @SILVER_INTERNAL_STAGE/customers/
FILE_FORMAT = (FORMAT_NAME = PARQUET_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO PRODUCTS
FROM @SILVER_INTERNAL_STAGE/products/
FILE_FORMAT = (FORMAT_NAME = PARQUET_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO STORES
FROM @SILVER_INTERNAL_STAGE/stores/
FILE_FORMAT = (FORMAT_NAME = PARQUET_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO ORDERS
FROM @SILVER_INTERNAL_STAGE/orders/
FILE_FORMAT = (FORMAT_NAME = PARQUET_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO ORDER_ITEMS
FROM @SILVER_INTERNAL_STAGE/order_items/
FILE_FORMAT = (FORMAT_NAME = PARQUET_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO PAYMENTS
FROM @SILVER_INTERNAL_STAGE/payments/
FILE_FORMAT = (FORMAT_NAME = PARQUET_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;